// Стык LoginServer ↔ GameServer (ADR-0005 п.2: сетевой gRPC, LS — сервер
// внутреннего порта, GS — клиент). Аутентификации нет: внутренняя граница
// доверия, дефолт bind 127.0.0.1.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: loginlink.proto

package loginlink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginLink_RegisterGameServer_FullMethodName = "/loginlink.v1.LoginLink/RegisterGameServer"
	LoginLink_ValidateSession_FullMethodName    = "/loginlink.v1.LoginLink/ValidateSession"
)

// LoginLinkClient is the client API for LoginLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginLinkClient interface {
	// Регистрация GS: ответный поток живёт, пока GS подключён; закрытие потока
	// (обрыв/вытеснение) убирает сервер из ServerList.
	RegisterGameServer(ctx context.Context, in *RegisterGameServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterEvent], error)
	// Однократная валидация ключей сессии (replay-защита).
	ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionReply, error)
}

type loginLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginLinkClient(cc grpc.ClientConnInterface) LoginLinkClient {
	return &loginLinkClient{cc}
}

func (c *loginLinkClient) RegisterGameServer(ctx context.Context, in *RegisterGameServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoginLink_ServiceDesc.Streams[0], LoginLink_RegisterGameServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterGameServerRequest, RegisterEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoginLink_RegisterGameServerClient = grpc.ServerStreamingClient[RegisterEvent]

func (c *loginLinkClient) ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSessionReply)
	err := c.cc.Invoke(ctx, LoginLink_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginLinkServer is the server API for LoginLink service.
// All implementations must embed UnimplementedLoginLinkServer
// for forward compatibility.
type LoginLinkServer interface {
	// Регистрация GS: ответный поток живёт, пока GS подключён; закрытие потока
	// (обрыв/вытеснение) убирает сервер из ServerList.
	RegisterGameServer(*RegisterGameServerRequest, grpc.ServerStreamingServer[RegisterEvent]) error
	// Однократная валидация ключей сессии (replay-защита).
	ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionReply, error)
	mustEmbedUnimplementedLoginLinkServer()
}

// UnimplementedLoginLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginLinkServer struct{}

func (UnimplementedLoginLinkServer) RegisterGameServer(*RegisterGameServerRequest, grpc.ServerStreamingServer[RegisterEvent]) error {
	return status.Error(codes.Unimplemented, "method RegisterGameServer not implemented")
}
func (UnimplementedLoginLinkServer) ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedLoginLinkServer) mustEmbedUnimplementedLoginLinkServer() {}
func (UnimplementedLoginLinkServer) testEmbeddedByValue()                   {}

// UnsafeLoginLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginLinkServer will
// result in compilation errors.
type UnsafeLoginLinkServer interface {
	mustEmbedUnimplementedLoginLinkServer()
}

func RegisterLoginLinkServer(s grpc.ServiceRegistrar, srv LoginLinkServer) {
	// If the following call panics, it indicates UnimplementedLoginLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginLink_ServiceDesc, srv)
}

func _LoginLink_RegisterGameServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterGameServerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoginLinkServer).RegisterGameServer(m, &grpc.GenericServerStream[RegisterGameServerRequest, RegisterEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoginLink_RegisterGameServerServer = grpc.ServerStreamingServer[RegisterEvent]

func _LoginLink_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginLinkServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginLink_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginLinkServer).ValidateSession(ctx, req.(*ValidateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginLink_ServiceDesc is the grpc.ServiceDesc for LoginLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loginlink.v1.LoginLink",
	HandlerType: (*LoginLinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateSession",
			Handler:    _LoginLink_ValidateSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterGameServer",
			Handler:       _LoginLink_RegisterGameServer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loginlink.proto",
}
