// Стык LoginServer ↔ GameServer (ADR-0005 п.2: сетевой gRPC, LS — сервер
// внутреннего порта, GS — клиент). Аутентификации нет: внутренняя граница
// доверия, дефолт bind 127.0.0.1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: loginlink.proto

package loginlink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterGameServerRequest — регистрация мира при старте GS.
type RegisterGameServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HexId         []byte                 `protobuf:"bytes,1,opt,name=hex_id,json=hexId,proto3" json:"hex_id,omitempty"` // идентификатор мира; повторная регистрация заменяет запись
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                // внешний адрес для ServerList
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"` // имя мира: журналы/онлайн-статистика, на проводе ServerList его нет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGameServerRequest) Reset() {
	*x = RegisterGameServerRequest{}
	mi := &file_loginlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGameServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGameServerRequest) ProtoMessage() {}

func (x *RegisterGameServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGameServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterGameServerRequest) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGameServerRequest) GetHexId() []byte {
	if x != nil {
		return x.HexId
	}
	return nil
}

func (x *RegisterGameServerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterGameServerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterGameServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RegisterEvent — событие потока регистрации (LS → GS).
type RegisterEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RegisterEvent_Ack
	//	*RegisterEvent_Displaced
	//	*RegisterEvent_Kick
	Kind          isRegisterEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEvent) Reset() {
	*x = RegisterEvent{}
	mi := &file_loginlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvent) ProtoMessage() {}

func (x *RegisterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvent.ProtoReflect.Descriptor instead.
func (*RegisterEvent) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterEvent) GetKind() isRegisterEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RegisterEvent) GetAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Kind.(*RegisterEvent_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RegisterEvent) GetDisplaced() *Displaced {
	if x != nil {
		if x, ok := x.Kind.(*RegisterEvent_Displaced); ok {
			return x.Displaced
		}
	}
	return nil
}

func (x *RegisterEvent) GetKick() *Kick {
	if x != nil {
		if x, ok := x.Kind.(*RegisterEvent_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

type isRegisterEvent_Kind interface {
	isRegisterEvent_Kind()
}

type RegisterEvent_Ack struct {
	Ack *RegisterAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // регистрация принята
}

type RegisterEvent_Displaced struct {
	Displaced *Displaced `protobuf:"bytes,2,opt,name=displaced,proto3,oneof"` // вытеснен новой регистрацией того же hexID: терминально, без реконнекта
}

type RegisterEvent_Kick struct {
	Kick *Kick `protobuf:"bytes,3,opt,name=kick,proto3,oneof"` // кик игрока; реализация — фаза 4+
}

func (*RegisterEvent_Ack) isRegisterEvent_Kind() {}

func (*RegisterEvent_Displaced) isRegisterEvent_Kind() {}

func (*RegisterEvent_Kick) isRegisterEvent_Kind() {}

// RegisterAck — назначенный ID записи ServerList (стабилен при замене по hexID).
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint32                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_loginlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAck) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

// Displaced — маркер вытеснения (пустое сообщение).
type Displaced struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Displaced) Reset() {
	*x = Displaced{}
	mi := &file_loginlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Displaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Displaced) ProtoMessage() {}

func (x *Displaced) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Displaced.ProtoReflect.Descriptor instead.
func (*Displaced) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{3}
}

// Kick — запрос отключения игрока (фаза 3: заглушка с журналом).
type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_loginlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{4}
}

func (x *Kick) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Kick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ValidateSessionRequest — ключи сессии игрока, входящего на GS.
type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	LoginOk1      int32                  `protobuf:"varint,2,opt,name=login_ok1,json=loginOk1,proto3" json:"login_ok1,omitempty"`
	LoginOk2      int32                  `protobuf:"varint,3,opt,name=login_ok2,json=loginOk2,proto3" json:"login_ok2,omitempty"`
	PlayOk1       int32                  `protobuf:"varint,4,opt,name=play_ok1,json=playOk1,proto3" json:"play_ok1,omitempty"`
	PlayOk2       int32                  `protobuf:"varint,5,opt,name=play_ok2,json=playOk2,proto3" json:"play_ok2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_loginlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateSessionRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ValidateSessionRequest) GetLoginOk1() int32 {
	if x != nil {
		return x.LoginOk1
	}
	return 0
}

func (x *ValidateSessionRequest) GetLoginOk2() int32 {
	if x != nil {
		return x.LoginOk2
	}
	return 0
}

func (x *ValidateSessionRequest) GetPlayOk1() int32 {
	if x != nil {
		return x.PlayOk1
	}
	return 0
}

func (x *ValidateSessionRequest) GetPlayOk2() int32 {
	if x != nil {
		return x.PlayOk2
	}
	return 0
}

// ValidateSessionReply — вердикт; успех изымает сессию однократно.
type ValidateSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionReply) Reset() {
	*x = ValidateSessionReply{}
	mi := &file_loginlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionReply) ProtoMessage() {}

func (x *ValidateSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_loginlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionReply.ProtoReflect.Descriptor instead.
func (*ValidateSessionReply) Descriptor() ([]byte, []int) {
	return file_loginlink_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateSessionReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_loginlink_proto protoreflect.FileDescriptor

const file_loginlink_proto_rawDesc = "" +
	"\n" +
	"\x0floginlink.proto\x12\floginlink.v1\"n\n" +
	"\x19RegisterGameServerRequest\x12\x15\n" +
	"\x06hex_id\x18\x01 \x01(\fR\x05hexId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa9\x01\n" +
	"\rRegisterEvent\x12-\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.loginlink.v1.RegisterAckH\x00R\x03ack\x127\n" +
	"\tdisplaced\x18\x02 \x01(\v2\x17.loginlink.v1.DisplacedH\x00R\tdisplaced\x12(\n" +
	"\x04kick\x18\x03 \x01(\v2\x12.loginlink.v1.KickH\x00R\x04kickB\x06\n" +
	"\x04kind\"*\n" +
	"\vRegisterAck\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\rR\bserverId\"\v\n" +
	"\tDisplaced\"8\n" +
	"\x04Kick\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa2\x01\n" +
	"\x16ValidateSessionRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1b\n" +
	"\tlogin_ok1\x18\x02 \x01(\x05R\bloginOk1\x12\x1b\n" +
	"\tlogin_ok2\x18\x03 \x01(\x05R\bloginOk2\x12\x19\n" +
	"\bplay_ok1\x18\x04 \x01(\x05R\aplayOk1\x12\x19\n" +
	"\bplay_ok2\x18\x05 \x01(\x05R\aplayOk2\",\n" +
	"\x14ValidateSessionReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xc6\x01\n" +
	"\tLoginLink\x12\\\n" +
	"\x12RegisterGameServer\x12'.loginlink.v1.RegisterGameServerRequest\x1a\x1b.loginlink.v1.RegisterEvent0\x01\x12[\n" +
	"\x0fValidateSession\x12$.loginlink.v1.ValidateSessionRequest\x1a\".loginlink.v1.ValidateSessionReplyB.Z,github.com/udisondev/l2go/internal/loginlinkb\x06proto3"

var (
	file_loginlink_proto_rawDescOnce sync.Once
	file_loginlink_proto_rawDescData []byte
)

func file_loginlink_proto_rawDescGZIP() []byte {
	file_loginlink_proto_rawDescOnce.Do(func() {
		file_loginlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loginlink_proto_rawDesc), len(file_loginlink_proto_rawDesc)))
	})
	return file_loginlink_proto_rawDescData
}

var file_loginlink_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_loginlink_proto_goTypes = []any{
	(*RegisterGameServerRequest)(nil), // 0: loginlink.v1.RegisterGameServerRequest
	(*RegisterEvent)(nil),             // 1: loginlink.v1.RegisterEvent
	(*RegisterAck)(nil),               // 2: loginlink.v1.RegisterAck
	(*Displaced)(nil),                 // 3: loginlink.v1.Displaced
	(*Kick)(nil),                      // 4: loginlink.v1.Kick
	(*ValidateSessionRequest)(nil),    // 5: loginlink.v1.ValidateSessionRequest
	(*ValidateSessionReply)(nil),      // 6: loginlink.v1.ValidateSessionReply
}
var file_loginlink_proto_depIdxs = []int32{
	2, // 0: loginlink.v1.RegisterEvent.ack:type_name -> loginlink.v1.RegisterAck
	3, // 1: loginlink.v1.RegisterEvent.displaced:type_name -> loginlink.v1.Displaced
	4, // 2: loginlink.v1.RegisterEvent.kick:type_name -> loginlink.v1.Kick
	0, // 3: loginlink.v1.LoginLink.RegisterGameServer:input_type -> loginlink.v1.RegisterGameServerRequest
	5, // 4: loginlink.v1.LoginLink.ValidateSession:input_type -> loginlink.v1.ValidateSessionRequest
	1, // 5: loginlink.v1.LoginLink.RegisterGameServer:output_type -> loginlink.v1.RegisterEvent
	6, // 6: loginlink.v1.LoginLink.ValidateSession:output_type -> loginlink.v1.ValidateSessionReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_loginlink_proto_init() }
func file_loginlink_proto_init() {
	if File_loginlink_proto != nil {
		return
	}
	file_loginlink_proto_msgTypes[1].OneofWrappers = []any{
		(*RegisterEvent_Ack)(nil),
		(*RegisterEvent_Displaced)(nil),
		(*RegisterEvent_Kick)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loginlink_proto_rawDesc), len(file_loginlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loginlink_proto_goTypes,
		DependencyIndexes: file_loginlink_proto_depIdxs,
		MessageInfos:      file_loginlink_proto_msgTypes,
	}.Build()
	File_loginlink_proto = out.File
	file_loginlink_proto_goTypes = nil
	file_loginlink_proto_depIdxs = nil
}
